### ISSUE TITLE
1-dimensional artifacts inside of isolines

### ISSUE THREAD

**Issue by ericyoungberg** [conveyal/jsolines#42]
Our team noticed that there are scattered dots and lines in the middle of isolines. From the file you linked to from your previous algorithm, you have [a line of code that likely filters out these small holes](https://github.com/conveyal/r5/blob/master/src/main/java/com/conveyal/r5/analyst/IsochroneFeature.java#L308) via an area calculation. 

We have a PR ready that fixes the issue if you are willing to take it. Our solution is to identify 2D holes by checking that the quantity of unique vertices is at least 3.

__Before__
![isolines-1D](https://user-images.githubusercontent.com/6749126/66834960-a22d7b80-ef2c-11e9-96cf-6b6d9cefba05.png)

__After__
![isolines-without-1D](https://user-images.githubusercontent.com/6749126/66835694-fedd6600-ef2d-11e9-808e-85614ff1e978.png)

**Comment by trevorgerhardt** [comment]
Hi! Yes, we would appreciate a PR that addresses this issue. Thanks!
